version: '3'
services:
  xampp:
    image: tomsik68/xampp:7.3.7
    ports:
      - "80:80"
    volumes:
      - ./config/php.ini:/opt/lampp/etc/php.ini
      - .:/www
    networks:
      - webgis-geodetic

  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres.dockerfile
      args:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    env_file: .env
    networks:
      - webgis-geodetic

  fastapi:
    build:
      context: .
      dockerfile: dockerfiles/fastapi.dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - webgis-geodetic

networks:
  webgis-geodetic:
    driver: bridge
